services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: team-calendar-pb
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
    environment:
      PB_ENCRYPTION_KEY: ${PB_ENCRYPTION_KEY:-00KXc2wDu28uWboLccLKNiOekYd11D2/+gAtmXH9h70=}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: team-calendar-app
    ports:
      - "3000:3000"
    environment:
      POCKETBASE_INTERNAL_URL: http://pocketbase:8090
      NEXT_PUBLIC_POCKETBASE_URL: http://localhost:8090
      NODE_ENV: development
    depends_on:
      pocketbase:
        condition: service_started
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  pocketbase_data:

